# Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Cho phép sử dụng NFC pins làm GPIO
CONFIG_NFCT_PINS_AS_GPIOS=y

# Split keyboard qua Bluetooth
CONFIG_ZMK_SPLIT=y

# Tăng độ ổn định Bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Tăng số profile BT (tối đa 5 thiết bị)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Tiết kiệm pin
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000