# Bật kết nối 2 mảnh (Split)
CONFIG_ZMK_SPLIT=y

# Chuyển chân NFC (P0.09, P0.10) thành chân GPIO bình thường (QUAN TRỌNG)
CONFIG_NFCT_PINS_AS_GPIOS=y

# Tăng công suất Bluetooth để kết nối ổn định hơn (nếu cần)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Bật hỗ trợ Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y