# BẬT LOGGING ĐỂ XEM ENCODER HOẠT ĐỘNG
CONFIG_ZMK_USB_LOGGING=y

# Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# GPIO
CONFIG_NFCT_PINS_AS_GPIOS=y

# Tăng log level để xem chi tiết
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_EC11_LOG_LEVEL_DBG=y